package config

import (
	"fmt"
	"os"
	"path/filepath"

	"github.com/BurntSushi/toml"
)

// Config holds all same-telegram configuration.
type Config struct {
	Bot    BotConfig    `toml:"bot"`
	Notify NotifyConfig `toml:"notify"`
	Digest DigestConfig `toml:"digest"`
	Watch  WatchConfig  `toml:"watch"`
}

// BotConfig holds Telegram bot settings.
type BotConfig struct {
	Token          string  `toml:"token"`
	AllowedUserIDs []int64 `toml:"allowed_user_ids"`
}

// NotifyConfig controls which notifications are sent.
type NotifyConfig struct {
	SessionEnd bool `toml:"session_end"`
	Decisions  bool `toml:"decisions"`
	Handoffs   bool `toml:"handoffs"`
}

// DigestConfig controls the daily digest.
type DigestConfig struct {
	Enabled bool   `toml:"enabled"`
	Time    string `toml:"time"` // HH:MM in local time
}

// WatchConfig controls file-watching for company-hq directories.
type WatchConfig struct {
	Enabled   bool              `toml:"enabled"`
	ExtraDirs map[string]string `toml:"extra_dirs"` // path -> category (review/decision/report)
}

// DefaultConfig returns a config with sensible defaults.
func DefaultConfig() *Config {
	return &Config{
		Notify: NotifyConfig{
			SessionEnd: true,
			Decisions:  true,
			Handoffs:   true,
		},
		Digest: DigestConfig{
			Enabled: true,
			Time:    "08:00",
		},
		Watch: WatchConfig{
			Enabled: true,
		},
	}
}

// configDir returns ~/.same/
func configDir() string {
	home, _ := os.UserHomeDir()
	return filepath.Join(home, ".same")
}

// ConfigPath returns the path to the telegram config file.
func ConfigPath() string {
	return filepath.Join(configDir(), "telegram.toml")
}

// SocketPath returns the path to the daemon unix socket.
func SocketPath() string {
	return filepath.Join(configDir(), "telegram.sock")
}

// PidPath returns the path to the daemon PID file.
func PidPath() string {
	return filepath.Join(configDir(), "telegram.pid")
}

// LogPath returns the path to the daemon log file.
func LogPath() string {
	return filepath.Join(configDir(), "telegram.log")
}

// Load reads the config from ~/.same/telegram.toml.
func Load() (*Config, error) {
	path := ConfigPath()
	cfg := DefaultConfig()

	data, err := os.ReadFile(path)
	if err != nil {
		if os.IsNotExist(err) {
			return nil, fmt.Errorf("config not found at %s — run 'same-telegram setup' first", path)
		}
		return nil, fmt.Errorf("read config: %w", err)
	}

	md, err := toml.Decode(string(data), cfg)
	if err != nil {
		return nil, fmt.Errorf("parse config: %w", err)
	}

	// Warn about unknown keys
	for _, key := range md.Undecoded() {
		fmt.Fprintf(os.Stderr, "same-telegram: WARNING: unknown key %q in %s\n", key.String(), path)
	}

	if cfg.Bot.Token == "" {
		return nil, fmt.Errorf("bot.token is required in %s", path)
	}
	if len(cfg.Bot.AllowedUserIDs) == 0 {
		return nil, fmt.Errorf("bot.allowed_user_ids is required in %s (security: whitelist your Telegram user ID)", path)
	}

	return cfg, nil
}

// GenerateTemplate writes a commented config template to ~/.same/telegram.toml.
func GenerateTemplate(token string, userID int64) error {
	dir := configDir()
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return fmt.Errorf("create config dir: %w", err)
	}

	content := fmt.Sprintf(`# same-telegram configuration
# Generated by: same-telegram setup

[bot]
# Telegram bot token from @BotFather
token = %q

# Telegram user IDs allowed to interact with this bot.
# Only these users can send commands. Others are silently ignored.
# Find your ID: message @userinfobot on Telegram
allowed_user_ids = [%d]

[notify]
# Which notifications to send to Telegram
session_end = true
decisions = true
handoffs = true

[digest]
# Daily digest of vault activity
enabled = true
time = "08:00"  # HH:MM in local time

[watch]
# Watch company-hq directories for new review/decision/report files
enabled = true
# Add extra directories to watch (path = category):
# [watch.extra_dirs]
# "/path/to/custom/dir" = "review"
`, token, userID)

	path := ConfigPath()
	if err := os.WriteFile(path, []byte(content), 0o600); err != nil {
		return fmt.Errorf("write config: %w", err)
	}
	return nil
}
